# Generated by Django 4.0.5 on 2022-07-20 08:11

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebook', '0003_brand_alter_notebook_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('SOM', 'SOM €'), ('USD', 'USD $')], default='USD', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14)),
                ('manufacturer', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.color')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessories.type')),
            ],
        ),
    ]
