# Generated by Django 4.0.5 on 2022-07-20 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='things'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accessories.type'),
        ),
    ]
