# Generated by Django 4.0.5 on 2022-07-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About us'},
        ),
    ]
